### PR TITLE
Added test cases

### PR DESCRIPTION
**Pull request by faridg**

### CODE REVIEW

**Comment by rossvalera** [comment]
Hi Farid,


I added comments to Exercise #3, and also ran them successfully. Take a look and let me know if you think any further changes needed.


Thanks

Marcos



________________________________

**Comment by faridg** [comment]
Hi Marcos,

Thanks.
Can't see the push & commit yet. 

Farid

**Comment by rossvalera** [comment]
Ok, try now.


________________________________

**Comment by faridg** [comment]
I see it now, looks great! I asked Prof.Sim, she said "yes", we need these test plans. Thanks.

**Comment by rossvalera** [comment]
Perfect!  Now we just need to send the details about our project through Blackboard (under Course Materials: 'Take Survey: Assignment 1 Repository Submission')


Here is the URL I am sending through the Blackboard survey:

https://github.com/faridg/inf1340_2015_asst1.git


Do you have any other comments to add or are we good to go?


Marcos

<https://github.com/faridg/inf1340_2015_asst1.git>

[https://avatars1.githubusercontent.com/u/8893711?v=3&s=400]<https://github.com/faridg/inf1340_2015_asst1.git>

faridg/inf1340_2015_asst1
inf1340_2015_asst1 - Assignment 1 for Inf1340, Fall 2015, UofT
Read more...<https://github.com/faridg/inf1340_2015_asst1.git>






________________________________

**Pull request merged**
